---
location: student11
file_name: student_11
  
mputty_name: Student_11
mputty_r1: 10.{{ ipv4_location }}.81  
mputty_r2: 10.{{ ipv4_location }}.82 
mputty_r3: 10.{{ ipv4_location }}.83 
mputty_r4: 10.{{ ipv4_location }}.84 
mputty_dls1: 10.{{ ipv4_location }}.85 
mputty_dls2: 10.{{ ipv4_location }}.86 
mputty_als1: 10.{{ ipv4_location }}.87
mputty_als2: 10.{{ ipv4_location }}.88   


