---
location: student4
file_name: student_04
mputty_name: Student_04
mputty_r1: 10.{{ ipv4_location }}.25  
mputty_r2: 10.{{ ipv4_location }}.26 
mputty_r3: 10.{{ ipv4_location }}.27 
mputty_r4: 10.{{ ipv4_location }}.28 
mputty_dls1: 10.{{ ipv4_location }}.29 
mputty_dls2: 10.{{ ipv4_location }}.30 
mputty_als1: 10.{{ ipv4_location }}.31
mputty_als2: 10.{{ ipv4_location }}.32 