---
location: student3
file_name: student_03
mputty_name: Student_03
mputty_r1: 10.{{ ipv4_location }}.17  
mputty_r2: 10.{{ ipv4_location }}.18 
mputty_r3: 10.{{ ipv4_location }}.19 
mputty_r4: 10.{{ ipv4_location }}.20 
mputty_dls1: 10.{{ ipv4_location }}.21 
mputty_dls2: 10.{{ ipv4_location }}.22 
mputty_als1: 10.{{ ipv4_location }}.23
mputty_als2: 10.{{ ipv4_location }}.24 